version: "3.5"

services:

  marketplace-prometheus:
    image: prom/prometheus
    container_name: marketplace-prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
