version: "3"


services:
  marketplace-db:
    image: postgres
    container_name: marketplace-db
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - marketplace-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  marketplace-db:


