version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip-172-31-27-233]
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_INITDB_ARGS: "--auth-local=trust"

volumes:
  db:

networks:
  default:
    external: true
    name: $DOCKER_NETWORK
